### ISSUE TITLE
PDFView - NullPointerException

### ISSUE THREAD

**Issue by brunopmoraes** [hazendaz/displaytag#8]
I got NullPointerException, because the Rectangle rect = writer.getBoxSize("art") is null, how i cant set this value by displaytag ?
`ERROR  o.d.export.PdfView.<init> / - {}
java.lang.NullPointerException: null
	at org.displaytag.export.PdfView$1.onEndPage(PdfView.java:167)
	at com.itextpdf.text.pdf.PdfDocument.endPage(PdfDocument.java:988)
	at com.itextpdf.text.pdf.PdfDocument.close(PdfDocument.java:882)
	at com.itextpdf.text.Document.close(Document.java:415)
	at org.displaytag.export.PdfView.doExport(PdfView.java:178)
	at org.displaytag.tags.TableTag.writeExport(TableTag.java:1608)
	at org.displaytag.tags.TableTag.doExport(TableTag.java:1486)
	at org.displaytag.tags.TableTag.doEndTag(TableTag.java:1334)
	at org.apache.jsp.Relatorios.Atendimento.conTmaTmeRes_jsp._jspx_meth_display_005ftable_005f0(conTmaTmeRes_jsp.java:324)
	at org.apache.jsp.Relatorios.Atendimento.conTmaTmeRes_jsp._jspService(conTmaTmeRes_jsp.java:211)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at lsf.servlet.filtros.FiltroLogin.doFilter(FiltroLogin.java:217)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at lsf.servlet.filtros.FiltroMDC.doFilter(FiltroMDC.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:613)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by hazendaz** [comment]
@brunopmoraes Can you check and see if this issue occurs on the original displaytag?  This fork has only been to limp along for those stuck on displaytag still as its really legacy.  I haven't used that area of the code so it could have been introduced through various library upgrades on this fork or has always existed.  If it exists on the old one too, that will give us something to go with that it's a pure bug.  If it doesn't exist there then it's probably going to be rather easy to find and you could raise a PR to fix it.
